name: Tests

on:
  push: ~
  pull_request: ~

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  php:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        php-versions: [ '7.4', '8.0', '8.1', '8.2', '8.3', '8.4', '8.5' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run tests
        run: vendor/bin/phpunit --log-junit phpunit-junit.xml

      - name: Publish test report
        if: always()
        uses: dorny/test-reporter@v3
        with:
          name: php (${{ matrix.php-versions }})
          path: phpunit-junit.xml
          reporter: phpunit-junit

  lowest:
    name: Lowest deps
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none

      - name: Download dependencies
        run: composer update --prefer-dist --no-progress --no-suggest --optimize-autoloader --prefer-stable --prefer-lowest

      - name: Run tests
        run: vendor/bin/phpunit --log-junit phpunit-junit.xml

      - name: Publish test report
        if: always()
        uses: dorny/test-reporter@v3
        with:
          name: Lowest deps
          path: phpunit-junit.xml
          reporter: phpunit-junit
