name: Static analysis

on:
  push: ~
  pull_request: ~

permissions:
  contents: read
  actions: read
  checks: write

env:
  PHP_MIN_VERSION: '7.4'
  PHP_DEFAULT_VERSION: '8.5'

jobs:
  phpstan:
    name: PHPStan
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_DEFAULT_VERSION }}
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: PHPStan
        run: vendor/bin/phpstan analyze --no-progress --error-format=github

  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_MIN_VERSION }}
          coverage: none
          tools: cs2pr

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: PHP-CS-Fixer
        run: vendor/bin/php-cs-fixer fix --dry-run --format=checkstyle | cs2pr

  psalm:
    name: Psalm
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_DEFAULT_VERSION }}
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Psalm
        run: vendor/bin/psalm --no-progress --output-format=github

  php-compatibility:
    name: PHP-Compatibility
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_DEFAULT_VERSION }}
          coverage: none
          tools: cs2pr

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: PHP-Compatibility
        run: composer run php-version-compatibility -- --report=checkstyle | cs2pr

  roave-backwards-compatibility-check:
    name: Roave BC Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_DEFAULT_VERSION }}
          coverage: none
          tools: backward-compatibility-check

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Check for BC breaks
        run: roave-backward-compatibility-check --format=github-actions

  composer-normalize:
    name: Composer Normalize
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_DEFAULT_VERSION }}
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Normalize
        run: composer normalize --dry-run
